package com.example.myludo;
import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import java.net.*;import java.util.*;
public class MainActivity extends Activity{
 GameView v; public void onCreate(Bundle b){super.onCreate(b);v=new GameView();setContentView(v);new Thread(this::listen).start();}
 String ip(){try{for(Enumeration<NetworkInterface>e=NetworkInterface.getNetworkInterfaces();e.hasMoreElements();){NetworkInterface n=e.nextElement();for(Enumeration<InetAddress>a=n.getInetAddresses();a.hasMoreElements();){InetAddress x=a.nextElement();String s=x.getHostAddress();if(!x.isLoopbackAddress()&&s.indexOf(':')<0)return s;}}}catch(Exception e){}return "unknown";}
 void listen(){try{DatagramSocket s=new DatagramSocket(45454);byte[]b=new byte[64];while(true){DatagramPacket q=new DatagramPacket(b,b.length);s.receive(q);String z=new String(q.getData(),0,q.getLength()).trim(),a[]=z.split(",");if(a.length==2){int pl=Integer.parseInt(a[0]),n=Integer.parseInt(a[1]);if(pl>0&&pl<5&&n>0&&n<7)runOnUiThread(()->v.cd(pl,n));}}}catch(Exception e){}}
 class GameView extends View{
  Paint p=new Paint(1);Random r=new Random();int mode=0,pl=0,d=0;int[] lp={0,0,0,0},sp={1,1,1,1};
  int[] sf={99,95,92,89,74,64,62,49,47,25},st={80,75,88,68,53,42,19,11,26,5},lf={2,7,8,15,21,28,36,51,71,78},lt={38,14,31,26,42,84,44,67,91,98};
  GameView(){super(MainActivity.this);p.setTypeface(Typeface.DEFAULT_BOLD);}
  void t(Canvas c,String s,float x,float y,float z,int col){p.setTextSize(z);p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
  void b(Canvas c,int y,String s){p.setColor(Color.rgb(65,52,100));c.drawRoundRect(30,y,getWidth()-30,y+64,18,18,p);t(c,s,50,y+41,18,Color.WHITE);}
  protected void onDraw(Canvas c){c.drawColor(Color.rgb(15,16,25));if(mode==0)menu(c);else if(mode==1)ludo(c);else if(mode==2)snake(c);else friends(c);}
  void menu(Canvas c){t(c,"🎲 MY LUDO",28,72,38,Color.WHITE);t(c,"Ludo • Saanp-Seedi • Friends",30,104,16,Color.LTGRAY);b(c,145,"🎲  LUDO");b(c,225,"🐍  SAANP-SEEDI");b(c,305,"👥  ONLINE FRIENDS");t(c,"Wi‑Fi IP: "+ip(),30,410,14,Color.LTGRAY);t(c,"Dice Controller same Wi‑Fi par connect hota hai.",30,437,13,Color.GRAY);}
  void head(Canvas c,String s){t(c,"‹   "+s,25,55,28,Color.WHITE);t(c,"Wi‑Fi IP: "+ip(),25,82,13,Color.LTGRAY);}
  void ludo(Canvas c){head(c,"LUDO");t(c,"Player "+(pl+1)+"   Dice: "+(d==0?"–":d),25,115,19,Color.WHITE);int top=135,size=Math.min(getWidth()-30,getHeight()-270),left=(getWidth()-size)/2;float q=size/15f;p.setColor(Color.WHITE);c.drawRect(left,top,left+size,top+size,p);int[]co={0xffe33e4d,0xff4b8fe8,0xff4caf65,0xfff0bd3d};for(int k=0;k<4;k++){int x=(k==1||k==2)?10:0,y=(k>1)?10:0;p.setColor(co[k]);c.drawRoundRect(left+x*q+3,top+y*q+3,left+(x+5)*q-3,top+(y+5)*q-3,16,16,p);}p.setStyle(Paint.Style.STROKE);p.setColor(0xff777777);for(int i=0;i<=15;i++){c.drawLine(left,top+i*q,left+size,top+i*q,p);c.drawLine(left+i*q,top,left+i*q,top+size,p);}p.setStyle(Paint.Style.FILL);t(c,"P1 "+lp[0]+"   P2 "+lp[1]+"   P3 "+lp[2]+"   P4 "+lp[3],20,top+size+27,13,Color.LTGRAY);b(c,top+size+42,"🎲 ROLL");t(c,"Controller se selected player ka dice yahan aayega.",25,top+size+120,12,Color.GRAY);}
  void snake(Canvas c){head(c,"SAANP-SEEDI");int size=Math.min(getWidth()-20,getHeight()-150),L=10,T=95;float q=size/10f;p.setColor(0xfff2dba9);c.drawRect(L,T,L+size,T+size,p);for(int rr=0;rr<10;rr++)for(int cc=0;cc<10;cc++){p.setColor(((rr+cc)&1)==0?0xffffefc5:0xffeed0a0);c.drawRect(L+cc*q,T+rr*q,L+(cc+1)*q,T+(rr+1)*q,p);int n=(9-rr)*10+(rr%2==0?cc+1:10-cc);t(c,""+n,L+cc*q+4,T+rr*q+15,10,Color.DKGRAY);}p.setStrokeWidth(6);p.setStyle(Paint.Style.STROKE);for(int i=0;i<sf.length;i++){ln(c,sf[i],st[i],Color.RED,L,T,q);ln(c,lf[i],lt[i],0xff238044,L,T,q);}p.setStyle(Paint.Style.FILL);t(c,"P1 "+sp[0]+"  P2 "+sp[1]+"  P3 "+sp[2]+"  P4 "+sp[3],20,T+size+27,14,Color.WHITE);b(c,T+size+42,"🎲 ROLL");}
  float[] pos(int n,int L,int T,float q){int z=n-1,row=9-z/10,col=z%10;if(row%2==1)col=9-col;return new float[]{L+(col+.5f)*q,T+(9-row+.5f)*q};}
  void ln(Canvas c,int a,int z,int col,int L,int T,float q){float[]x=pos(a,L,T,q),y=pos(z,L,T,q);p.setColor(col);c.drawLine(x[0],x[1],y[0],y[1],p);}
  void friends(Canvas c){head(c,"ONLINE FRIENDS");t(c,"👥 Friend Room",30,135,27,Color.WHITE);t(c,"Room code / friends lobby",30,168,15,Color.LTGRAY);b(c,205,"CREATE ROOM");b(c,285,"JOIN ROOM");t(c,"Real internet multiplayer ke liye backend",30,390,14,Color.YELLOW);t(c,"server connect karna zaroori hai.",30,415,14,Color.LTGRAY);t(c,"Main fake online sync ko complete game nahi bol raha.",30,442,13,Color.GRAY);}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=1)return true;float y=e.getY();if(mode==0){if(y>140&&y<220)mode=1;else if(y>220&&y<300)mode=2;else if(y>300&&y<390)mode=3;}else if(y<95)mode=0;else if(mode==1&&y>getHeight()-220){d=1+r.nextInt(6);lp[pl]=(lp[pl]+d)%57;pl=(pl+1)%4;}else if(mode==2&&y>getHeight()-120){int n=1+r.nextInt(6),v=Math.min(100,sp[pl]+n);for(int i=0;i<sf.length;i++)if(v==sf[i])v=st[i];for(int i=0;i<lf.length;i++)if(v==lf[i])v=lt[i];sp[pl]=v;pl=(pl+1)%4;}invalidate();return true;}
  void cd(int player,int dice){mode=1;pl=player-1;d=dice;lp[pl]=(lp[pl]+dice)%57;invalidate();}
 }
}